import * as constants from '../../constants';

test('Constants', () => {
  expect(constants).toEqual({
    "MIN_GENE_SYMBOL_DIGITS":3,
    "MIN_HGVS_INPUT_LENGTH":8,
    "PROTEIN_SEQUENCE_START_INDEX":1,
    "PROTEIN_NUMBER_MIN_LENGTH":11,
    "PROTEIN_NUMBER_MAX_LENGTH":11,
    "PROTEIN_ALPHABET":{
       "G":{
          "name":"Glycine",
          "symbol":"Gly"
       },
       "P":{
          "name":"Proline",
          "symbol":"Pro"
       },
       "A":{
          "name":"Alanine",
          "symbol":"Ala"
       },
       "V":{
          "name":"Valine",
          "symbol":"Val"
       },
       "L":{
          "name":"Leucine",
          "symbol":"Leu"
       },
       "I":{
          "name":"Isoleucine",
          "symbol":"Ile"
       },
       "M":{
          "name":"Methionine",
          "symbol":"Met"
       },
       "C":{
          "name":"Cysteine",
          "symbol":"Cys"
       },
       "F":{
          "name":"Phenylalanine",
          "symbol":"Phe"
       },
       "Y":{
          "name":"Tyrosine",
          "symbol":"Tyr"
       },
       "W":{
          "name":"Tryptophan",
          "symbol":"Trp"
       },
       "H":{
          "name":"Histidine",
          "symbol":"His"
       },
       "K":{
          "name":"Lysine",
          "symbol":"Lys"
       },
       "R":{
          "name":"Arginine",
          "symbol":"Arg"
       },
       "Q":{
          "name":"Glutamine",
          "symbol":"Gln"
       },
       "N":{
          "name":"Asparagine",
          "symbol":"Asn"
       },
       "E":{
          "name":"Glutamic Acid",
          "symbol":"Glu"
       },
       "D":{
          "name":"Aspartic Acid",
          "symbol":"Asp"
       },
       "S":{
          "name":"Serine",
          "symbol":"Ser"
       },
       "T":{
          "name":"Threonine",
          "symbol":"Thr"
       },
       "X":{
          "name":"X",
          "symbol":"X"
       }
    },
    "PROTEIN_ALPHABET_ARRAY":[
       {
          "key":"A",
          "name":"Alanine",
          "symbol":"Ala"
       },
       {
          "key":"C",
          "name":"Cysteine",
          "symbol":"Cys"
       },
       {
          "key":"D",
          "name":"Aspartic Acid",
          "symbol":"Asp"
       },
       {
          "key":"E",
          "name":"Glutamic Acid",
          "symbol":"Glu"
       },
       {
          "key":"F",
          "name":"Phenylalanine",
          "symbol":"Phe"
       },
       {
          "key":"G",
          "name":"Glycine",
          "symbol":"Gly"
       },
       {
          "key":"H",
          "name":"Histidine",
          "symbol":"His"
       },
       {
          "key":"I",
          "name":"Isoleucine",
          "symbol":"Ile"
       },
       {
          "key":"K",
          "name":"Lysine",
          "symbol":"Lys"
       },
       {
          "key":"L",
          "name":"Leucine",
          "symbol":"Leu"
       },
       {
          "key":"M",
          "name":"Methionine",
          "symbol":"Met"
       },
       {
          "key":"N",
          "name":"Asparagine",
          "symbol":"Asn"
       },
       {
          "key":"P",
          "name":"Proline",
          "symbol":"Pro"
       },
       {
          "key":"Q",
          "name":"Glutamine",
          "symbol":"Gln"
       },
       {
          "key":"R",
          "name":"Arginine",
          "symbol":"Arg"
       },
       {
          "key":"S",
          "name":"Serine",
          "symbol":"Ser"
       },
       {
          "key":"T",
          "name":"Threonine",
          "symbol":"Thr"
       },
       {
          "key":"V",
          "name":"Valine",
          "symbol":"Val"
       },
       {
          "key":"W",
          "name":"Tryptophan",
          "symbol":"Trp"
       },
       {
          "key":"X",
          "name":"X",
          "symbol":"X"
       },
       {
          "key":"Y",
          "name":"Tyrosine",
          "symbol":"Tyr"
       }
    ]
 });
});

